In [2]:
import pandas as pd
import os
import sys

# Add project root to path so we can import config
sys.path.append(os.path.abspath(".."))

from config.settings import PATHS

# Define the path to the raw data directory ,which is one level up from the current directory
RAW_PATH = f"../{PATHS['raw']}"

# Load all 4 datasets
incidents = pd.read_csv(f"{RAW_PATH}incidents.csv")
production = pd.read_csv(f"{RAW_PATH}production.csv")
maintenance = pd.read_csv(f"{RAW_PATH}maintenance.csv")
hse = pd.read_csv(f"{RAW_PATH}hse.csv")

print("✅ All 4 datasets loaded successfully")
print(f"Incidents: {incidents.shape}")
print(f"Production: {production.shape}")
print(f"Maintenance: {maintenance.shape}")
print(f"HSE: {hse.shape}")

✅ All 4 datasets loaded successfully
Incidents: (1000, 13)
Production: (1000, 13)
Maintenance: (1000, 12)
HSE: (1000, 14)

In [4]:
df = pd.read_csv(f"{RAW_PATH}maintenance.csv")

print(df["issued_date"].head(20))
print(df["resolved_date"].head(20))

0                     NaN
1     2026-06-29 21:28:30
2     2026-06-29 21:25:27
3     2026-06-29 21:26:47
4     2026-06-29 21:28:30
5     2026-06-29 21:28:10
6                     NaN
7     2026-06-29 21:27:10
8     2026-06-29 21:25:30
9                     NaN
10    2026-06-29 21:28:55
11    2026-06-29 21:26:33
12    2026-06-29 21:29:08
13    2026-06-29 21:24:59
14    2026-06-29 21:29:39
15    2026-06-29 21:25:22
16    2026-06-29 21:28:49
17                    NaN
18    2026-06-29 21:30:01
19    2026-06-29 21:26:36
Name: issued_date, dtype: str
0     2026-07-01 10:02:53.471038
1     2026-07-01 18:49:29.517485
2     2026-07-01 13:51:17.280951
3     2026-06-30 09:45:28.655926
4     2026-07-01 16:32:35.065605
5     2026-07-01 11:03:29.065241
6     2026-07-02 16:42:07.923061
7     2026-07-02 19:48:46.178972
8     2026-07-01 22:07:54.049602
9     2026-06-30 15:02:17.149413
10    2026-07-01 07:55:59.101748
11    2026-06-30 08:08:31.149430
12    2026-06-29 22:46:04.355234
13    2026-07-02 01:24:37.651372
14    2026-06-30 10:15:26.947110
15    2026-06-30 07:42:17.507341
16    2026-07-02 10:27:15.942838
17    2026-07-01 02:22:17.959079
18    2026-06-30 20:00:31.627296
19    2026-07-01 06:19:13.307308
Name: resolved_date, dtype: str

In [5]:
incidents.dtypes

incident_id             str
equipment_id            str
field                   str
team                    str
category                str
incident_date           str
incident_type           str
severity                str
status                  str
resolution_hours    float64
sla_breach              str
downtime_hours      float64
reported_by             str
dtype: object

In [6]:
incidents.isnull().sum()

incident_id           0
equipment_id          0
field                 0
team                  0
category              0
incident_date       154
incident_type         0
severity              0
status                0
resolution_hours      0
sla_breach          154
downtime_hours        0
reported_by           0
dtype: int64

In [7]:
# i am using print because i want to see multiple outputs in the notebook cell
print("Negative resolution_hours:", incidents[incidents["resolution_hours"] < 0]["resolution_hours"].count())
print("Negative downtime_hours:", incidents[incidents["downtime_hours"] < 0]["downtime_hours"].count())

Negative resolution_hours: 154
Negative downtime_hours: 0

In [11]:
print("Severity:", incidents["severity"].unique())
print("Status:", incidents["status"].unique())
print("Incident type:", incidents["incident_type"].unique())
print("SLA breach:", incidents["sla_breach"].unique())

Severity: <StringArray>
['High', 'Critical', 'Low', 'Medium']
Length: 4, dtype: str
Status: <StringArray>
['In Progress', 'Resolved', 'UNKNOWN', 'Open']
Length: 4, dtype: str
Incident type: <StringArray>
[             'Leak',         'Corrosion', 'Valve Malfunction',
 'Equipment Failure',     'Pressure Drop',      'Power Outage']
Length: 6, dtype: str
SLA breach: <StringArray>
['Yes', nan, 'No']
Length: 3, dtype: str

In [9]:
# Count of unique values per column
incidents.nunique()

incident_id         1000
equipment_id          10
field                  5
team                   4
category               5
incident_date        331
incident_type          6
severity               4
status                 4
resolution_hours     758
sla_breach             2
downtime_hours       759
reported_by          993
dtype: int64

In [12]:
# Check basic statistics for numerical columns
incidents[["resolution_hours", "downtime_hours"]].describe()

       resolution_hours  downtime_hours
count        1000.00000     1000.000000
mean            1.56205       10.179750
std            45.62865       10.948213
min           -99.00000        0.500000
25%             3.99000        2.565000
50%            10.40500        5.840000
75%            24.92750       14.040000
max            71.74000       61.330000

In [13]:
production.dtypes

production_id                   str
equipment_id                    str
field                           str
team                            str
category                        str
production_date                 str
oil_volume_bbl              float64
gas_volume_mcf              float64
water_volume_bbl            float64
choke_size                  float64
wellhead_pressure           float64
deferred_production_bbls    float64
operator                        str
dtype: object

In [14]:
production.isnull().sum()

production_id                 0
equipment_id                  0
field                         0
team                          0
category                      0
production_date             153
oil_volume_bbl                0
gas_volume_mcf                0
water_volume_bbl              0
choke_size                  153
wellhead_pressure           153
deferred_production_bbls    153
operator                      0
dtype: int64

In [16]:
production.columns

Index(['production_id', 'equipment_id', 'field', 'team', 'category',
       'production_date', 'oil_volume_bbl', 'gas_volume_mcf',
       'water_volume_bbl', 'choke_size', 'wellhead_pressure',
       'deferred_production_bbls', 'operator'],
      dtype='str')

In [21]:
print("Negative oil_volume_bbl:", production[production["oil_volume_bbl"] < 0]["oil_volume_bbl"].count())
print("Negative gas_volume_mcf:", production[production["gas_volume_mcf"] < 0]["gas_volume_mcf"].count())
print("Negative wellhead_pressure:", production[production["wellhead_pressure"] < 0]["wellhead_pressure"].count())
print("Negative water_volume_bbls:", production[production["water_volume_bbl"] < 0]["water_volume_bbl"].count())
print("Negative choke_size:", production[production["choke_size"] < 0]["choke_size"].count())
print("Negative deferred_production_bbls:", production[production["deferred_production_bbls"] < 0]["deferred_production_bbls"].count())

Negative oil_volume_bbl: 153
Negative gas_volume_mcf: 153
Negative wellhead_pressure: 0
Negative water_volume_bbls: 153
Negative choke_size: 0
Negative deferred_production_bbls: 0

In [22]:
print("Operator unique:", production["operator"].unique())

Operator unique: <StringArray>
[  'Kaitlyn Snyder',     'Kelly Palmer',       'Shawn Gill',
 'Michael Gonzalez',     'Tyler Dennis',     'Stephen Ware',
  'Melody Robinson',    'Michael Logan',       'Jay Mendez',
       'Luis Evans',
 ...
    'Cynthia Smith',      'George Ford',      'Nicole Hall',
     'Sara Shelton',    'Judy Jones MD',      'Jeremy Reed',
      'Andrew Long',    'Carolyn Smith',   'Sandra Ramirez',
    'Rebecca Woods']
Length: 995, dtype: str

In [24]:
production[production["operator"] == "Uknown"]

Empty DataFrame
Columns: [production_id, equipment_id, field, team, category, production_date, oil_volume_bbl, gas_volume_mcf, water_volume_bbl, choke_size, wellhead_pressure, deferred_production_bbls, operator]
Index: []

In [3]:
maintenance.columns

Index(['maintenance_id', 'equipment_id', 'field', 'team', 'category',
       'issued_date', 'resolved_date', 'maintenance_type',
       'maintenance_duration_hours', 'maintenance_cost', 'status', 'operator'],
      dtype='str')

In [4]:
maintenance.dtypes

maintenance_id                    str
equipment_id                      str
field                             str
team                              str
category                          str
issued_date                       str
resolved_date                     str
maintenance_type                  str
maintenance_duration_hours    float64
maintenance_cost              float64
status                            str
operator                          str
dtype: object

In [6]:
maintenance.isnull().sum()

maintenance_id                  0
equipment_id                    0
field                           0
team                            0
category                        0
issued_date                   132
resolved_date                   0
maintenance_type                0
maintenance_duration_hours      0
maintenance_cost                0
status                          0
operator                      132
dtype: int64

In [12]:
for col in maintenance.columns:
    print(f"{col}: {maintenance[col].nunique()}")

maintenance_id: 1000
equipment_id: 10
field: 5
team: 4
category: 5
issued_date: 329
resolved_date: 1000
maintenance_type: 4
maintenance_duration_hours: 818
maintenance_cost: 1000
status: 3
operator: 858

In [18]:
print("Maintenance type:", maintenance["maintenance_type"].unique())
print('status:', maintenance["status"].unique())

Maintenance type: <StringArray>
['Corrective', 'Preventive', 'Predictive', 'UNKNOWN']
Length: 4, dtype: str
status: <StringArray>
['In Progress', 'Open', 'Resolved']
Length: 3, dtype: str

In [25]:
print("UNKNOWN operators:", (maintenance["operator"] == "UNKNOWN").sum())

UNKNOWN operators: 0

In [ ]:
maintenance[["maintenance_cost","maintenance_duration_hours"]].describe()

       maintenance_cost  maintenance_duration_hours
count       1000.000000                 1000.000000
mean       25803.862510                   18.530650
std        14352.198047                   49.970478
min         1003.140000                  -99.000000
25%        13287.097500                   10.277500
50%        26075.335000                   30.575000
75%        38182.780000                   51.652500
max        49963.280000                   71.960000

In [26]:
hse.columns

Index(['hse_id', 'equipment_id', 'field', 'team', 'category', 'incident_date',
       'incident_type', 'severity', 'near_miss', 'days_lost', 'department',
       'location', 'reported_by', 'investigator'],
      dtype='str')

In [27]:
hse.dtypes

hse_id             str
equipment_id       str
field              str
team               str
category           str
incident_date      str
incident_type      str
severity           str
near_miss          str
days_lost        int64
department         str
location           str
reported_by        str
investigator       str
dtype: object

In [28]:
hse.isnull().sum()

hse_id             0
equipment_id       0
field              0
team               0
category           0
incident_date    152
incident_type      0
severity           0
near_miss          0
days_lost          0
department         0
location           0
reported_by        0
investigator     152
dtype: int64

In [29]:
hse.nunique()

hse_id           1000
equipment_id       10
field               5
team                4
category            5
incident_date     326
incident_type       6
severity            4
near_miss           2
days_lost          32
department          6
location            6
reported_by       997
investigator      846
dtype: int64

In [30]:
print("hse incident types:", hse["incident_type"].unique())
print("hse severity:", hse["severity"].unique())
print("hse location:", hse["location"].unique())
print("hse department:", hse["department"].unique())

hse incident types: <StringArray>
['Fall', 'Chemical Spill', 'Explosion', 'Gas Leak', 'Fire',
 'Equipment Strike']
Length: 6, dtype: str
hse severity: <StringArray>
['Low', 'Medium', 'Critical', 'High']
Length: 4, dtype: str
hse location: <StringArray>
[  'Compressor Area',      'Pump Station',      'Control Room',
          'Wellhead', 'Pipeline Junction',      'Storage Area']
Length: 6, dtype: str
hse department: <StringArray>
['Maintenance', 'Engineering', 'Operations', 'HSE', 'Logistics', 'UNKNOWN']
Length: 6, dtype: str

In [31]:
print("days_lost:", hse["days_lost"].describe())

days_lost: count    1000.00000
mean       -2.34300
std        41.73669
min       -99.00000
25%         3.00000
50%        12.00000
75%        21.00000
max        30.00000
Name: days_lost, dtype: float64